import { useState } from 'react'
import Head from 'next/head'

import { Button, TextField, InputAdornment } from '@mui/material'
import VisibilityIcon from '@mui/icons-material/Visibility'

export default function Home() {
  const [isLogin, setIsLogin] = useState(false)
  const [show, setShow] = useState(false)
  const [usuario, setUsuario] = useState({ username: '', contraseña: '' })
  const handleLogin = () => {
    if (usuario.username !== '' && usuario.contraseña !== '') {
      setIsLogin(true)
    }
  }
  return (
    <div>
      <Head>
        <title>Panaderia Bosque</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        style={{
          marginBottom: '3rem',
          backgroundColor: 'black',
          color: 'white',
          height: '50px',
        }}
      >
        navbar
      </div>
      <div>
        {isLogin ? (
          <h2>Bienvenido..{usuario.username}</h2>
        ) : (
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <form style={{ display: 'flex', flexDirection: 'column' }}>
              <TextField
                label='usuario'
                size='small'
                value={usuario.username}
                onChange={(e) =>
                  setUsuario({ ...usuario, username: e.target.value })
                }
                style={{ marginBottom: '1rem' }}
              />
              <TextField
                label='contraseña'
                size='small'
                value={usuario.contraseña}
                onChange={(e) =>
                  setUsuario({ ...usuario, contraseña: e.target.value })
                }
                style={{ marginBottom: '1rem' }}
                type='password'
                InputProps={{
                  endAdornment: (
                    <InputAdornment position='start'>
                      <VisibilityIcon />
                    </InputAdornment>
                  ),
                }}
              />
              <Button
                variant='outlined'
                size='small'
                onClick={() => handleLogin()}
              >
                Login
              </Button>
            </form>
          </div>
        )}
      </div>
      <footer
        style={{
          marginTop: '3rem',
          backgroundColor: 'black',
          color: 'white',
          height: '50px',
        }}
      >
        footer
      </footer>
    </div>
  )
}
